[workspace]
resolver = "2"
members = [
    "crates/bss-core",
    "crates/bss-data",
    "crates/bss-encoder",
    "crates/bss-valkey",
    "crates/bss-cli",
    "crates/bss-integration-tests",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
thiserror = "2.0"
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
envy = "0.4"
bytes = "1.12"
tracing = "0.1"
