[package]
name = "bss-data"
description = "Data loading for BehaviorSimilaritySearch."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"
